name: Update README with Recent Activity

on:
  schedule:
    # Saatte bir çalışır
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
